manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.99
      import:
        path-prefix: deps
        path: zephyr
        name-allowlist:
          - hostap
          - zephyr
          - mbedtls
          - nrfxlib
          - cmsis
          - hal_nordic