manifest:
  # remotes:
    # - name: nrfconnect
      # url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      # this is the sdk-nrf version, not the Zephyr version
      revision: v3.0.2
      url: https://github.com/nrfconnect/sdk-nrf
      import:
        path-prefix: deps
        name-allowlist:
          - zephyr
          - cmsis
          - cmsis_6
          - hal_nordic
          - loramac-node
          - mcuboot
          - mbedtls
          - zcbor
          - nrfxlib
          - nrf_hw_models
          - trusted-firmware-m
          - segger
          - oberon-psa-crypto