name: Build

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/Dockerfile
          push: false
          load: true
          tags: zephyr-build:latest

      - name: Build
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -e ZEPHYR_BASE=/workspace/zephyr \
            zephyr-build:latest west build -p
          mkdir -p .out
          cp build/zephyr/zephyr.elf .out/
          cp build/zephyr/zephyr.bin .out/
          cp build/zephyr/zephyr.hex .out/

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: .out/