name: Build

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tylercgarcia/zephyr:posix-0.17.0SDK
      credentials:
        username: TylerCGarcia
        password: ${{ secrets.DOCKER_PULL }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Clone the repo to a subdirectory, so we can initialize the Zephyr
          # workspace in the parent directory.
          path: LoRa-BLE-Sensor
          # Fetch all history, so we can use git describe
          fetch-depth: 0
          # west init -l zephyr
          # west update --narrow -o=--depth=1 
          # west build -p

      - name: ♻️ Initialize Zephyr Workspace
        run: |
          cd LoRa-BLE-Sensor
          scripts/init_ci.sh

      - name: Build
        run: |
          ls -a
          cd LoRa-BLE-Sensor
          west build app -p

      - name: 📦 Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: custom-docker-image-artifacts
          path: LoRa-BLE-Sensor/build/zephyr/zephyr.elf