name: Build

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.27.3
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      # - name: Clean up disk space
      #   run: |
      #     swapoff -a
      #     rm -f /swapfile
      #     apt clean
      #     docker rmi $(docker image ls -aq)
      #     df -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set variables
        id: vars
        run: |
             echo "branch=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
             echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Initialize
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build 
        run: |
          west build -p
          mkdir -p .out
          cp build/zephyr/zephyr.elf .out/
          cp build/zephyr/zephyr.bin .out/
          cp build/zephyr/zephyr.hex .out/
  
      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: .out/