name: Build

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/Dockerfile
          push: false
          load: true
          tags: zephyr-build:latest

      - name: ♻️ Initialize Zephyr Workspace
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -e ZEPHYR_BASE=/workspace/zephyr \
            zephyr-build:latest bash -c '
              cd /workspace && \
              rm -rf .west && \
              west init -l . && \
              west update --narrow -o=--depth=1 && \
              west build -p
              '

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: .out/