name: Build

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tylercgarcia/zephyr:arm-0.17.0SDK
      credentials:
        username: TylerCGarcia
        password: ${{ secrets.DOCKER_PULL }}
    env:
      # Tell cmake where to find the zephyr sdk
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - uses: actions/checkout@v4
        with:
          # Clone the repo to a subdirectory
          path: LoRa-BLE-Sensor
          # Fetch all history, so we can use git describe
          fetch-depth: 0

      - name: ♻️ Initialize Zephyr Workspace
        run: |
          cd LoRa-BLE-Sensor
          scripts/init_ci.sh

      - name: Build
        run: |
          ls -a
          cd LoRa-BLE-Sensor
          . .venv/bin/activate
          west build app -b lora_ble_sensor --pristine --sysbuild

      # - name: 📦 Save Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Build-Results-${{ github.ref_name }}
      #     path: |
      #       LoRa-BLE-Sensor/build/app/zephyr/zephyr.elf
      #     # LoRa-BLE-Sensor/build/mcuboot/zephyr/zephyr.elf
      - name: Set artifact name
        id: artifact-name
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "name=Build-Results-$TAG_NAME-${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "name=Build-Results-${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: 📦 Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: |
            LoRa-BLE-Sensor/build/app/zephyr/zephyr.elf
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tylercgarcia/zephyr:posix-0.17.0SDK
      credentials:
        username: TylerCGarcia
        password: ${{ secrets.DOCKER_PULL }}
    env:
      # Tell cmake where to find the zephyr sdk
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - uses: actions/checkout@v4
        with:
          # Clone the repo to a subdirectory
          path: LoRa-BLE-Sensor
          # Fetch all history, so we can use git describe
          fetch-depth: 0

      - name: ♻️ Initialize Zephyr Workspace
        run: |
          cd LoRa-BLE-Sensor
          scripts/init_ci.sh

      - name: Build
        run: |
          ls -a
          cd LoRa-BLE-Sensor
          . .venv/bin/activate
          west twister -W -T tests/

      - name: 📦 Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: Test-Results
          path: |
            LoRa-BLE-Sensor/twister-out/testplan.json
            LoRa-BLE-Sensor/twister-out/twister_report.xml
            LoRa-BLE-Sensor/twister-out/twister_suite_report.xml
            LoRa-BLE-Sensor/twister-out/twister.json
            LoRa-BLE-Sensor/twister-out/testplan.json
            LoRa-BLE-Sensor/twister-out/**/*.log